// Created by iWeb 3.0.1 local-build-20101030

setTransparentGifURL('../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_1:new IWShadow({blurRadius:1,offset:new IWPoint(0.0000,0.0000),color:'#000000',opacity:0.750000}),stroke_3:new IWStrokeParts([{rect:new IWRect(-2,2,4,56),url:'CHMView_files/stroke_32.png'},{rect:new IWRect(-2,-2,4,4),url:'CHMView_files/stroke_33.png'},{rect:new IWRect(2,-2,56,4),url:'CHMView_files/stroke_34.png'},{rect:new IWRect(58,-2,4,4),url:'CHMView_files/stroke_35.png'},{rect:new IWRect(58,2,4,56),url:'CHMView_files/stroke_36.png'},{rect:new IWRect(58,58,4,4),url:'CHMView_files/stroke_37.png'},{rect:new IWRect(2,58,56,4),url:'CHMView_files/stroke_38.png'},{rect:new IWRect(-2,58,4,4),url:'CHMView_files/stroke_39.png'}],new IWSize(60,60)),shadow_2:new IWShadow({blurRadius:1,offset:new IWPoint(0.0000,0.0000),color:'#000000',opacity:0.750000}),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,56),url:'CHMView_files/stroke_16.png'},{rect:new IWRect(-2,-2,4,4),url:'CHMView_files/stroke_17.png'},{rect:new IWRect(2,-2,56,4),url:'CHMView_files/stroke_18.png'},{rect:new IWRect(58,-2,4,4),url:'CHMView_files/stroke_19.png'},{rect:new IWRect(58,2,4,56),url:'CHMView_files/stroke_20.png'},{rect:new IWRect(58,58,4,4),url:'CHMView_files/stroke_21.png'},{rect:new IWRect(2,58,56,4),url:'CHMView_files/stroke_22.png'},{rect:new IWRect(-2,58,4,4),url:'CHMView_files/stroke_23.png'}],new IWSize(60,60)),stroke_0:new IWStrokeParts([{rect:new IWRect(-3,3,6,87),url:'CHMView_files/stroke.png'},{rect:new IWRect(-3,-3,6,6),url:'CHMView_files/stroke_1.png'},{rect:new IWRect(3,-3,146,6),url:'CHMView_files/stroke_2.png'},{rect:new IWRect(149,-3,6,6),url:'CHMView_files/stroke_3.png'},{rect:new IWRect(149,3,6,87),url:'CHMView_files/stroke_4.png'},{rect:new IWRect(149,90,6,6),url:'CHMView_files/stroke_5.png'},{rect:new IWRect(3,90,146,6),url:'CHMView_files/stroke_6.png'},{rect:new IWRect(-3,90,6,6),url:'CHMView_files/stroke_7.png'}],new IWSize(152,93)),shadow_0:new IWShadow({blurRadius:1,offset:new IWPoint(0.0000,0.0000),color:'#000000',opacity:0.750000}),stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,56),url:'CHMView_files/stroke_24.png'},{rect:new IWRect(-2,-2,4,4),url:'CHMView_files/stroke_25.png'},{rect:new IWRect(2,-2,56,4),url:'CHMView_files/stroke_26.png'},{rect:new IWRect(58,-2,4,4),url:'CHMView_files/stroke_27.png'},{rect:new IWRect(58,2,4,56),url:'CHMView_files/stroke_28.png'},{rect:new IWRect(58,58,4,4),url:'CHMView_files/stroke_29.png'},{rect:new IWRect(2,58,56,4),url:'CHMView_files/stroke_30.png'},{rect:new IWRect(-2,58,4,4),url:'CHMView_files/stroke_31.png'}],new IWSize(60,60))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function photocastSubscribe()
{photocastHelper("http://ipad-deng.appspot.com/ipad-deng/CHMView/rss.xml");}
function onPageLoad()
{loadMozillaCSS('CHMView_files/CHMViewMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');detectBrowser();adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');fixAllIEPNGs('../Media/transparent.gif');Widget.onload();fixupAllIEPNGBGs();fixupIECSS3Opacity('id7');applyEffects()}
function onPageUnload()
{Widget.onunload();}
